"""add user_id to course table

Revision ID: 6affafabe478
Revises: cc424ae69ecc
Create Date: 2025-03-13 13:14:14.492031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6affafabe478'
down_revision = 'cc424ae69ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_record', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
