"""remove user foreignkey

Revision ID: 8e7b4fe9e8c2
Revises: 786fce3aa589
Create Date: 2025-02-04 16:16:45.648629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7b4fe9e8c2'
down_revision = '786fce3aa589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('todo_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_foreign_key('todo_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
