"""add stu resources

Revision ID: cc424ae69ecc
Revises: 0819dca2b540
Create Date: 2025-03-13 12:24:10.526469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc424ae69ecc'
down_revision = '0819dca2b540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('todo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_replies',
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('original_id', 'reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_replies')
    op.drop_table('thread')
    op.drop_table('course_record')
    # ### end Alembic commands ###
